### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: Failed to parse webhook URL

### ISSUE THREAD

**Issue by ScremerMemer** [jagrosh/Vortex#144]
**Hey so basically im getting the above mentioned error even though my webhook url is correct and valid, please help**

 Full error:
 `Exception in thread "main" java.lang.IllegalArgumentException: Failed to parse webhook URL
        at club.minnced.discord.webhook.WebhookClientBuilder.<init>(WebhookClientBuilder.java:84)
        at com.jagrosh.vortex.logging.TextUploader.lambda$new$0(TextUploader.java:45)
        at java.base/java.util.ArrayList.forEach(Unknown Source)
        at com.jagrosh.vortex.logging.TextUploader.<init>(TextUploader.java:45)
        at com.jagrosh.vortex.Vortex.<init>(Vortex.java:87)
        at com.jagrosh.vortex.Vortex.main(Vortex.java:334)`

**Comment by MichailiK** [comment]
[Self-hosting the bot is not supported.](https://github.com/jagrosh/Vortex#can-i-self-host-vortex)
